export const MONTHS = ['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь']
export const MONTHS_SHORT = ['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек']

export const EXPENSE_CATS = {
  transport:     { l: 'Связь и транспорт', c: '#7c9cf5', i: '🚌' },
  hygiene:       { l: 'Гигиена и уход',    c: '#5cc98a', i: '🧼' },
  beauty:        { l: 'Красота',           c: '#e87c6b', i: '💅' },
  home:          { l: 'Дом (разовое)',     c: '#a07cf5', i: '🏠' },
  clothing:      { l: 'Одежда и обувь',   c: '#f57ca0', i: '👗' },
  pet:           { l: 'Питомец',          c: '#f5a57c', i: '🐾' },
  meds:          { l: 'Аптека',           c: '#5cc9c9', i: '💊' },
  leisure:       { l: 'Электронки',       c: '#c8a96e', i: '💨' },
  subscriptions: { l: 'Подписки',         c: '#7c9cf5', i: '💻' },
  food_out:      { l: 'Фастфуд',          c: '#f5a57c', i: '🍔' },
  custom:        { l: 'Моё',              c: '#f57ca0', i: '✏️' },
}

export const FOOD_CATS = {
  dairy:  { l: 'Молочное',       c: '#e0dbd0', i: '🥛' },
  meat:   { l: 'Мясо',          c: '#e87c6b', i: '🥩' },
  veg:    { l: 'Овощи',         c: '#5cc98a', i: '🥗' },
  carbs:  { l: 'Крупы и паста', c: '#c8a96e', i: '🍝' },
  frozen: { l: 'Замороженное',  c: '#7c9cf5', i: '🧊' },
  drinks: { l: 'Напитки',       c: '#a07cf5', i: '☕' },
  sauces: { l: 'Соусы и базовое', c: '#f5a57c', i: '🫙' },
  want:   { l: 'Хочу',          c: '#f57ca0', i: '🌟' },
  salad:  { l: 'К салатам',     c: '#5cc9c9', i: '🥙' },
  rare:   { l: 'Редко',         c: '#6b7cf5', i: '📦' },
}

export const EXPENSE_ITEMS = [
  { id:'t1', n:'Связь (Вика)',        cat:'transport',     w:'vika',   p:700,   r:true },
  { id:'t2', n:'Связь (Илья)',        cat:'transport',     w:'ilya',   p:750,   r:true },
  { id:'t3', n:'Проезд (Вика)',       cat:'transport',     w:'vika',   p:1500,  r:true },
  { id:'t4', n:'Проезд (Илья)',       cat:'transport',     w:'ilya',   p:1500,  r:true },
  { id:'t5', n:'ВПН',                cat:'transport',     w:'shared', p:1600,  r:true },
  { id:'t6', n:'Подписка Claude',     cat:'subscriptions', w:'ilya',   p:1499,  r:true },
  { id:'t7', n:'Сервер DayZ',         cat:'subscriptions', w:'ilya',   p:1800,  r:true },
  { id:'t8', n:'Фастфуд (начало)',    cat:'food_out',      w:'shared', p:2000,  r:true },
  { id:'t9', n:'Фастфуд (конец)',     cat:'food_out',      w:'shared', p:2000,  r:true },
  { id:'b1', n:'Ногти',              cat:'beauty',        w:'vika',   p:2000,  r:true },
  { id:'b2', n:'Краска для волос',    cat:'beauty',        w:'vika',   p:420,   r:false, m:[] },
  { id:'b3', n:'Маски для лица',      cat:'beauty',        w:'shared', p:280,   r:false, m:[] },
  { id:'b4', n:'Пенка',              cat:'beauty',        w:'vika',   p:500,   r:false, m:[] },
  { id:'b5', n:'Энзимная пудра',      cat:'beauty',        w:'shared', p:350,   r:false, m:[] },
  { id:'b6', n:'Моя шея',            cat:'beauty',        w:'vika',   p:3500,  r:false, m:[] },
  { id:'b7', n:'Духи (Вика)',         cat:'beauty',        w:'vika',   p:1000,  r:false, m:[] },
  { id:'b8', n:'Духи (Илья)',         cat:'beauty',        w:'ilya',   p:1000,  r:false, m:[] },
  { id:'e1', n:'Жижа (электронка)',   cat:'leisure',       w:'shared', p:1000,  r:true },
  { id:'e2', n:'Испарители',          cat:'leisure',       w:'shared', p:900,   r:true },
  { id:'h6', n:'Прокладки',          cat:'hygiene',       w:'vika',   p:220,   r:true },
  { id:'h1', n:'Зубная паста',        cat:'hygiene',       w:'shared', p:200,   r:false, m:[] },
  { id:'h2', n:'Мыло для рук (5 л)', cat:'hygiene',       w:'shared', p:365,   r:false, m:[] },
  { id:'h3', n:'Мыло для посуды',    cat:'hygiene',       w:'shared', p:471,   r:false, m:[] },
  { id:'h4', n:'Капсулы посудомойка', cat:'hygiene',       w:'shared', p:795,   r:false, m:[] },
  { id:'h5', n:'Капсулы стиралка',   cat:'hygiene',       w:'shared', p:893,   r:false, m:[] },
  { id:'h7', n:'Гель для душа',       cat:'hygiene',       w:'shared', p:675,   r:false, m:[] },
  { id:'h8', n:'Шампунь',            cat:'hygiene',       w:'shared', p:423,   r:false, m:[] },
  { id:'h9', n:'Антижир',            cat:'hygiene',       w:'shared', p:178,   r:false, m:[] },
  { id:'h10',n:'Губки',              cat:'hygiene',       w:'shared', p:137,   r:false, m:[] },
  { id:'h11',n:'Полотенца кухонные', cat:'hygiene',       w:'shared', p:400,   r:false, m:[] },
  { id:'h12',n:'Дезодорант (Вика)',  cat:'hygiene',       w:'vika',   p:200,   r:false, m:[] },
  { id:'h13',n:'Дезодорант (Илья)',  cat:'hygiene',       w:'ilya',   p:300,   r:false, m:[] },
  { id:'h14',n:'Ватные палочки',     cat:'hygiene',       w:'shared', p:50,    r:false, m:[] },
  { id:'h15',n:'Презервативы',       cat:'hygiene',       w:'shared', p:852,   r:false, m:[], note:'на 3 мес' },
  { id:'h16',n:'Смазка',            cat:'hygiene',       w:'shared', p:175,   r:false, m:[] },
  { id:'h17',n:'Тест на беременность', cat:'hygiene',     w:'vika',   p:614,   r:false, m:[] },
  { id:'h18',n:'От прыщей',          cat:'hygiene',       w:'shared', p:150,   r:false, m:[] },
  { id:'o1', n:'Тарелки',           cat:'home',          w:'shared', p:254,   r:false, m:[5] },
  { id:'o2', n:'Сито',              cat:'home',          w:'shared', p:212,   r:false, m:[5] },
  { id:'o3', n:'Духовка',           cat:'home',          w:'shared', p:5000,  r:false, m:[5] },
  { id:'o4', n:'Ключ',              cat:'home',          w:'shared', p:800,   r:false, m:[5] },
  { id:'o5', n:'Удлинители',        cat:'home',          w:'shared', p:1300,  r:false, m:[5] },
  { id:'o6', n:'Контейнеры',        cat:'home',          w:'shared', p:400,   r:false, m:[5] },
  { id:'o7', n:'Кастрюля',          cat:'home',          w:'shared', p:2000,  r:false, m:[5] },
  { id:'o8', n:'Номер',             cat:'home',          w:'shared', p:171,   r:false, m:[] },
  { id:'cl1',n:'Нижнее бельё',      cat:'clothing',      w:'shared', p:4000,  r:false, m:[] },
  { id:'cl2',n:'Обувь',             cat:'clothing',      w:'shared', p:5000,  r:false, m:[] },
  { id:'cl3',n:'Куртка зимняя',     cat:'clothing',      w:'vika',   p:5000,  r:false, m:[] },
  { id:'cl4',n:'Куртка осенняя',    cat:'clothing',      w:'vika',   p:4000,  r:false, m:[] },
  { id:'cl5',n:'Одежда (Синсей)',       cat:'clothing',      w:'shared', p:10000, r:false, m:[], note:'копим' },
  { id:'cl6',n:'Хобби',             cat:'clothing',      w:'shared', p:3000,  r:false, m:[] },
  { id:'p1', n:'Корм',              cat:'pet',           w:'shared', p:420,   r:false, m:[] },
  { id:'p2', n:'Наполнитель',       cat:'pet',           w:'shared', p:230,   r:false, m:[] },
  { id:'m1', n:'Цитрамон',          cat:'meds',          w:'shared', p:120,   r:false, m:[] },
  { id:'m2', n:'Омепразол',         cat:'meds',          w:'shared', p:200,   r:false, m:[] },
  { id:'m3', n:'Обезболивающее',    cat:'meds',          w:'shared', p:250,   r:false, m:[] },
  { id:'m4', n:'Лоперамид',         cat:'meds',          w:'shared', p:40,    r:false, m:[] },
  { id:'m5', n:'Пластыри',          cat:'meds',          w:'shared', p:200,   r:false, m:[] },
  { id:'m6', n:'Супрастин',         cat:'meds',          w:'shared', p:160,   r:false, m:[] },
  { id:'m7', n:'Риностоп',          cat:'meds',          w:'shared', p:140,   r:false, m:[] },
  { id:'m8', n:'Левомеколь',        cat:'meds',          w:'shared', p:300,   r:false, m:[] },
  { id:'m9', n:'Акридерм',          cat:'meds',          w:'shared', p:190,   r:false, m:[] },
]

export const FOOD_ITEMS = [
  { id:'fd1', n:'Молоко х2',           cat:'dairy',  wk:[1,2,3,4], p:200 },
  { id:'fd2', n:'Сметана',             cat:'dairy',  wk:[1,2,3,4], p:100 },
  { id:'fd3', n:'Творог',              cat:'dairy',  wk:[1,3],     p:134 },
  { id:'fd4', n:'Сыр',                cat:'dairy',  wk:[1,3],     p:200 },
  { id:'fm1', n:'Куриное филе',        cat:'meat',   wk:[1,3],     p:500 },
  { id:'fm2', n:'Фарш х2',            cat:'meat',   wk:[1,3],     p:500 },
  { id:'fm3', n:'Колбаса',            cat:'meat',   wk:[1,3],     p:300 },
  { id:'fv1', n:'Огурцы',             cat:'veg',    wk:[1,3],     p:100 },
  { id:'fv2', n:'Помидоры',           cat:'veg',    wk:[1,3],     p:100 },
  { id:'fv3', n:'Лук',                cat:'veg',    wk:[1,3,4],   p:40  },
  { id:'fv4', n:'Яйца',               cat:'veg',    wk:[1],       p:80  },
  { id:'fc1', n:'Макароны',           cat:'carbs',  wk:[1,3],     p:77  },
  { id:'fc2', n:'Спагетти',           cat:'carbs',  wk:[1,3],     p:101 },
  { id:'fc3', n:'Каша',               cat:'carbs',  wk:[1,3],     p:150 },
  { id:'fc4', n:'Гречка',             cat:'carbs',  wk:[1,3],     p:80  },
  { id:'fc5', n:'Рис',                cat:'carbs',  wk:[1,3],     p:120 },
  { id:'fc6', n:'Сахар',              cat:'carbs',  wk:[1,3],     p:142 },
  { id:'fc7', n:'Картофель',          cat:'carbs',  wk:[2],       p:100 },
  { id:'fc8', n:'Лаваш',              cat:'carbs',  wk:[2,4],     p:90  },
  { id:'ff1', n:'Наггетсы',           cat:'frozen', wk:[1,3],     p:150 },
  { id:'ff2', n:'Пельмени 1 кг',      cat:'frozen', wk:[1,3],     p:180 },
  { id:'ff3', n:'Вареники',           cat:'frozen', wk:[1,3],     p:170 },
  { id:'fd5', n:'Сок',                cat:'drinks', wk:[1,2,3,4], p:100 },
  { id:'fd6', n:'Кофе х2',            cat:'drinks', wk:[1,2,3,4], p:320 },
  { id:'fd7', n:'Чай',                cat:'drinks', wk:[1],       p:300 },
  { id:'fs1', n:'Томатная паста',     cat:'sauces', wk:[1,3],     p:90  },
  { id:'fs2', n:'Масло',              cat:'sauces', wk:[1],       p:140 },
  { id:'fsl1',n:'Кукуруза',           cat:'salad',  wk:[],        p:0,  salad:true },
  { id:'fsl2',n:'Горошек',            cat:'salad',  wk:[],        p:0,  salad:true },
  { id:'fsl3',n:'Огурцы солёные',     cat:'salad',  wk:[],        p:0,  salad:true },
  { id:'fw1', n:'Самса',              cat:'want',   wk:[],        p:60, want:true },
  { id:'fw2', n:'Косичка',            cat:'want',   wk:[],        p:53, want:true },
  { id:'fw3', n:'Йогурты',            cat:'want',   wk:[],        p:70, want:true },
  { id:'fw4', n:'Актимель',           cat:'want',   wk:[],        p:40, want:true },
  { id:'fw5', n:'Ряженка',            cat:'want',   wk:[],        p:100,want:true },
  { id:'fw6', n:'Чипсы',              cat:'want',   wk:[],        p:100,want:true },
  { id:'fw7', n:'Конфеты',            cat:'want',   wk:[],        p:500,want:true },
  { id:'fw8', n:'Печенье / Пай',      cat:'want',   wk:[],        p:80, want:true },
  { id:'fw9', n:'Батончики',          cat:'want',   wk:[],        p:200,want:true },
  { id:'fw10',n:'Чоко Бой',           cat:'want',   wk:[],        p:57, want:true },
  { id:'fw11',n:'Морковка по-корейски',cat:'want',  wk:[],        p:0,  want:true },
  { id:'fr1', n:'Соль',               cat:'rare',   wk:[],        p:50, rare:true },
  { id:'fr2', n:'Уксус',              cat:'rare',   wk:[],        p:80, rare:true },
  { id:'fr3', n:'Свёкла',             cat:'rare',   wk:[],        p:36, rare:true },
  { id:'fr4', n:'Капуста',            cat:'rare',   wk:[],        p:52, rare:true },
  { id:'fr5', n:'Лимон',              cat:'rare',   wk:[],        p:120,rare:true },
]

export const fmt = n => n ? n.toLocaleString('ru-RU') + ' ₽' : '—'

export const SAL1 = 18000
export const SAL2 = 26000
